version: 2
updates:
  #Enable dependabot for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: 
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    allow:
      - dependency-type: "direct"
    versioning-strategy: "auto"

  #Enable dependabot for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"
    labels:
      - "actions"
    commit-message:
      prefix: "chore(actions):"
    versioning-strategy: "auto"

  #Enable dependabot for docker
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
    commit-message:
      prefix: "chore(docker):"
    allow:
      - dependency-type: "direct"
    versioning-strategy: "auto"
